fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\User\Entity\User
  profile:
    form:
      type: App\User\UseCase\UpdateUser\Controller\UpdateUserType
  registration:
    form:
      type: App\User\UseCase\RegisterUser\Controller\RegisterUserType
  from_email:
    address: "test@domain.com"
    sender_name: "test@domain.com"