fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\User\Entity\User
  service:
    mailer: App\Notifier\AppNotifier
  profile:
    form:
      type: App\User\UseCase\UpdateUser\Controller\UpdateUserType
  registration:
    confirmation:
      enabled: false
    form:
      type: App\User\UseCase\RegisterUser\Controller\RegisterUserType
  from_email:
    address: '%env(resolve:SENDER_EMAIL)%'
    sender_name: '%env(resolve:SENDER_EMAIL)%'